---
name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch: {}
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-2
  
jobs:
  deploy-dev:
    strategy:
      matrix:
        node-version: [16.x]
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: Fooji/create-aws-profile-action@v1
        with:
          key: $AWS_ACCESS_KEY_ID
          secret: $AWS_SECRET_ACCESS_KEY
          region: eu-east-2

      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: yarn install
      - run: yarn deploy --stage prod